#!/usr/bin/env bash
# Script that install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
