#!/usr/bin/env bash
# script to install and setup nginx
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
